require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - tmp/**/*

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  SupportedStylesAlignWith:
    - keyword
    - variable

Layout/LineLength:
  Max: 120
  Exclude:
    - config/initializers/simple_form_foundation.rb

Metrics/BlockLength:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectActual:
  Exclude:
    - spec/routing/**/*_spec.rb

RSpec/DescribeClass:
  Enabled: false
  Exclude:
    - spec/features/**/*_spec.rb

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/RepeatedDescription:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/EmptyMethod:
  EnforcedStyle: expanded
  SupportedStyles:
    - compact
    - expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
  Exclude:
    - config/initializers/simple_form_foundation.rb

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true
