name: Rspec

on: [push]

jobs:
  quality:
    runs-on: ubuntu-latest
    name: Quality
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - name: Install Rubocop
        run: |
          gem install bundler
          bundle
      - name: Check code
        run: |
          cp .env.example .env
          bin/quality
  test:
    env:
      POSTGRES_USER: md_notes
      POSTGRES_PASSWORD: md_notes
      POSTGRES_DB: md_notes
      RAILS_ENV: test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: md_notes_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
    - name: Build and test with Rake
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        cp .env.example .env
        bundle exec rails db:create
        bundle exec rails db:migrate
        bin/rspec
    - name: Upload coverage results
      uses: actions/upload-artifact@master
      with:
        name: coverage-report
        path: coverage
